
const ru = {
    plan: "0% Рассрочка",
    punk: "Пункт выдачи",
    call: "Заказать звонок",
    question: "Часто задаваемые вопросы",
    cat: "Категории",
    order: "Мои заказы",
    like: "Избранное",
    shop: "Корзина",
    user: "Регистрация",
    all: "Подробнее",
    phone: "Смартфоны",
    best: "по лучшим ценам",
    tv: "Телевизоры",
    home: "для дома",
    machine: "Бытовые техники",
    trend: "В Тренде",
    got: "в наличии",
    month: "в месяц",
    more: "Показать еще",
    brend: "Бренды",
    buy: "Распродажа",
    menu: "Главная",
    sport: "Спорт",
    boots: "Спортивные кроссовки",
};
const uz = {
    plan: "0% To'lov",
    call: "Qo'ng'iroqni talab qiling",
    punk: "Qabul qilish punkti",
    question: "Ko'p so'raladigan savollar",
    cat:"Kategoriyalar",
    order: "Buyurtmalar",
    like: "Sevimli",
    shop: "Do'kon",
    user: "Registratsiya",
    all: "Batafsil",
    phone: "Smartfonlar",
    best: "eng yaxshi narxlarda",
    tv: "Televizorlar",
    home: "uy uchun",
    machine: "Maishiy texnika",
    trend: "Trendda",
    got: "sotuvda mavjud",
    month: "oyiga",
    more: "ko'proq ko'rish",
    brend: "Brendlar",
    buy: "Sotish",
    menu: "Bosh sahifa",
    sport: "Sport",
    boots: "Sport poyabzali"
};


export const languages = { uz, ru };
